version: '3'
services:
  proposta:
    build:
        dockerfile: ./docker/Dockerfile
        context: .
    container_name: proposta
    ports:
        - 8082:8081
    environment: 
      URL_DB: jdbc:postgresql://postgres-dev:5433/proposta
      DB_USER: morango
      DB_PASSWORD: vitamina
      URL_PROPOSTA: http://analise:9999
      URL_CARTOES: http://contas:8888

    depends_on: 
        - "postgres-dev"

  postgres-dev:
    image: "postgres:alpine"
    expose:
        - 5433
    ports: 
      - 5433:5433
    volumes:
      - postgres-dev-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: morango
      POSTGRES_PASSWORD: vitamina
      POSTGRES_DB: proposta
      POSTGRES_HOST: postgres
    command: -p 5433
    

  analise:
    image: 'zupacademy/analise-financeira'
    ports:
      - 9999:9999
    environment:
      SERVER_PORT: 9999
      LOG_LEVEL: INFO
      URL_SISTEMA_CARTAO: http://contas:8888/api/cartoes
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  contas:
    image: 'zupacademy/contas'
    ports:
      - 8888:8888
    environment:
      SERVER_PORT: 8888
      LOG_LEVEL: INFO
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces



volumes:
  grafana-volume:
  prometheus-volume:
  postgres-volume:
  postgres-dev-volume:
